<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta http-equiv="Content-Language" content="ru"></head><body><h1 class="V8SH_pagetitle">КатегорияОшибки.ОшибкаКонфигурации (ErrorCategory.ConfigurationError)</h1><p class="V8SH_title">КатегорияОшибки (ErrorCategory)</p><p class="V8SH_heading">ОшибкаКонфигурации (ConfigurationError)</p><div class="__SINCE_SHOW_STYLE__"><p class="not_used">Доступен, начиная с версии 8.3.21.</p></div><p class="V8SH_chapter">Описание:</p>Ошибка возникла вследствие исключения, вызванного прикладным разработчиком во время нештатной ситуации при вызове метода или процедуры (из оператора ВызватьИсключение).<br>Например: неправильное количество параметров, неправильное значение параметра, некорректное внутреннее состояние.<br>Рекомендуется устанавливать данную категорию при генерации исключений, которые сигнализируют об ошибке в конфигурации.<p class="V8SH_chapter">Использование в версии:</p><p class="V8SH_versionInfo">Доступен, начиная с версии 8.3.21.</p><HR><p>&nbsp;&nbsp;&nbsp;&nbsp; <a href=http://www.1centerprise.com/devlinks?C="id=00058O02709A13110;lan=ru" target="_blank">Методическая информация</a></p></body></html>